version: '3.7'
services:
  scope:
    image: weaveworks/scope:1.13.2
    network_mode: host
    container_name: scope
    privileged: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    command:
      - "--mode=app --weave=false"
