version: '2'
services:
  scope:
    image: weaveworks/scope:1.13.2
    container_name: scope
    network_mode: "host"
    pid: "host"
    privileged: true
    ports:
      - 4040:4040
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    command:
      - "--probe.docker=true --weave=false"
