version: '2'
services:
  scope:
    image: weaveworks/scope:1.13.2
    network_mode: "host"
    pid: "host"
    privileged: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    command:
      - "--probe.docker=true --weave=false"
